language: node_js
sudo: required
dist: trusty
node_js: stable
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - rm google-chrome-stable_current_amd64.deb
  - "npm install -g bower"
  - "bower install"
  - "npm i -g web-component-tester@4.3.1 istanbul https://github.com/t2ym/web-component-tester-istanbul/tarball/0.10.1"
  - "npm install coveralls"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - wct
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
deploy:
  provider: script
  script: "bash ./gpages.sh cheonhyangzhang paper-typeahead-input"
  on:
    branch: release
